version: 2.1
jobs:
  lint:
    docker:
      - image: hseeberger/scala-sbt:8u312_1.5.8_2.13.7
    steps:
      - checkout
      - run: sbt ++2.13.7! check
  test213:
    docker:
      - image: hseeberger/scala-sbt:17.0.1_1.5.8_2.13.7
    steps:
      - checkout
      - run: sbt ++2.13.7! compile rezilienceJVM/test:compile
  test_dotty:
    docker:
      - image: hseeberger/scala-sbt:17.0.1_1.5.8_3.1.0
    steps:
      - checkout
      - run: sbt ++3.1.0! rezilienceJVM/test:compile
  release:
    docker:
      - image: hseeberger/scala-sbt:17.0.1_1.5.8_2.13.7
    steps:
      - checkout
      - run: git fetch --tags
      - run: apt install -y gnupg
      - run: export GPG_TTY=$(tty)
      - run: echo $PGP_SECRET | base64 --decode | gpg --batch --import
      - run: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
      - run: sbt ci-release

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test213:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - test_dotty:
          requires:
            - lint
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - release:
          requires:
            - test213
            - test_dotty
          filters:
            branches:
              only:
                - master
                - zio-2.0